version: "3"

services: 
    back:
        build: ./back/.
        volumes: 
            - "./back/src:/app/src"
        links: 
            - db
    db:
        image: mariadb
        ports: 
            - "3333:3306"
        environment: 
            MYSQL_ROOT_PASSWORD : root
    front:
        build: ./Font/.
        ports:
            -"80:80"
        links: 
            - back
    
