version: "3.7"
services: 
    web:
        image: nginx
        ports:
            - "89:80"
        links: 
            - php
        environment: 
            PHP_HOST: php
    php:
        image: php-zendserver
        links: 
            - db
        environment: 
            DB_HOST: db
    db:
        image: mariadb
        ports: 
            - "3333:3306"
        environment: 
            MYSQL_ROOT_PASSWORD : root
